### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by ItsSelis**
+Added Add Server GUI
+Added that Users can now Edit Servers (Server > Edit) - File gets opened by Default Software for .cfg Files
+Added Remove Server Button
+Added SteamCMD to Install new Server (AppID Needed)
+Added SteamCMD Update for Selected Server (AppID Needed)
+Added German Language
+Updated .gitignore
+Updated Assembly Version
+Updated TODO/Changelog inside the Source Code
+Updated README.md
+Fixed Minor Bugs

### CODE REVIEW

**Comment by blt950** [comment]
This is some nice pull, I'll look through it soon! 👍

**Comment by blt950** [comment]
Thank you for dedicating your time to improve Server Manager, it's nice to see someone wants to continue a bit on this project. I've looked through the code and it's all good. Though before I do a merge I'd like you to catch exceptions related to SteamCMD @Sirlionfur 

I've tried both install and update options, but always end up with a runtime error.

> ************** Exception Text **************
> System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
>    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at Server_Manager.SCMD_InstallServer.btnAddServer_Click(Object sender, EventArgs e) in C:\WAMP64\www\Server-Manager-Pull\Server Manager\SCMD_InstallServer.cs:line 43
>    at System.Windows.Forms.Control.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnClick(EventArgs e)
>    at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    at System.Windows.Forms.Button.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by ItsSelis** [comment]
I got that Error often too until I got to the point when it worked. I can try to fix it sometime, but at the moment I have a lot of exams to learn for my school :/

**Comment by blt950** [comment]
I understand, do you know what causes the error? Are you using any external executables it doesn't reach? Such as for the steamcmd perhaps? Since I didn't get it to work at all.

**Comment by ItsSelis** [comment]
Yeah, I think it's trying to open the SteamCMD in the steamcmd folder, but it cant reach/find it.

**Comment by blt950** [comment]
Alright, I'll merge it, but not create a new release of it as it's still very WIP.

**Pull request merged**
